"""added_lesson_location

Revision ID: 64351dddc548
Revises: 923c4931254d
Create Date: 2023-04-01 19:54:09.855994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64351dddc548'
down_revision = '923c4931254d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SCHEDULE', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('STD_SCHEDULE', sa.Column('location', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('STD_SCHEDULE', 'location')
    op.drop_column('SCHEDULE', 'location')
    # ### end Alembic commands ###
