"""unique_index_for_lesson_dt

Revision ID: 75e6e4a82216
Revises: 8f4815a7879e
Create Date: 2023-11-18 12:32:00.851460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e6e4a82216'
down_revision = '8f4815a7879e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_absolute_start_time', 'SCHEDULE', ['absolute_start_time'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_absolute_start_time', table_name='SCHEDULE')
    # ### end Alembic commands ###
