"""free_lessons

Revision ID: 8f4815a7879e
Revises: c737091a66ad
Create Date: 2023-06-11 15:22:18.676291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '8f4815a7879e'
down_revision = 'c737091a66ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FREE_LESSON',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.String(length=16), nullable=False),
    sa.Column('time_end', sa.String(length=16), nullable=False),
    sa.Column('is_active', ENUM('YES', 'NO', name='yesno', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FREE_LESSON')
    # ### end Alembic commands ###
