"""added_reminder_switch

Revision ID: 923c4931254d
Revises: bd101458df85
Create Date: 2023-02-24 21:06:20.365045

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '923c4931254d'
down_revision = 'bd101458df85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USERS_REMINDERS', sa.Column('is_active', sa.Enum('YES', 'NO', name='yesno'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USERS_REMINDERS', 'is_active')
    # ### end Alembic commands ###
