"""Initial

Revision ID: bd101458df85
Revises: 
Create Date: 2023-02-24 20:42:08.402430

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd101458df85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_name', sa.String(length=30), nullable=False),
    sa.Column('fullname', sa.String(length=200), nullable=False),
    sa.Column('secret_code', sa.String(length=60), nullable=True),
    sa.Column('telegram_login', sa.String(length=60), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Enum('YES', 'NO', name='yesno'), nullable=False),
    sa.Column('dump_state', sa.Enum('TABLE_DELETED', 'BOT_DELETED', 'TO_SYNC', 'ACTIVE', name='dumpstates'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_name')
    )
    op.create_table('SCHEDULE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('absolute_start_time', sa.DateTime(), nullable=False),
    sa.Column('time_start', sa.String(length=16), nullable=False),
    sa.Column('time_end', sa.String(length=16), nullable=False),
    sa.Column('type', sa.Enum('ONLINE', 'OFFLINE', 'RENT', name='schedulerecordtype'), nullable=False),
    sa.Column('dump_state', sa.Enum('TABLE_DELETED', 'BOT_DELETED', 'TO_SYNC', 'ACTIVE', name='dumpstates'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('STD_SCHEDULE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_the_week', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.String(length=16), nullable=False),
    sa.Column('time_end', sa.String(length=16), nullable=False),
    sa.Column('type', sa.Enum('ONLINE', 'OFFLINE', 'RENT', name='schedulerecordtype'), nullable=False),
    sa.Column('dump_state', sa.Enum('TABLE_DELETED', 'BOT_DELETED', 'TO_SYNC', 'ACTIVE', name='dumpstates'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USERS_COMMENTS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['USERS.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USERS_REMINDERS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('remind_minutes_before', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USERS_ROLES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USERS_ROLES')
    op.drop_table('USERS_REMINDERS')
    op.drop_table('USERS_COMMENTS')
    op.drop_table('STD_SCHEDULE')
    op.drop_table('SCHEDULE')
    op.drop_table('USERS')
    # ### end Alembic commands ###
