"""gc_event_id

Revision ID: c5a583453c74
Revises: 64351dddc548
Create Date: 2023-04-16 12:26:53.875670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a583453c74'
down_revision = '64351dddc548'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SCHEDULE', sa.Column('gc_event_id', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SCHEDULE', 'gc_event_id')
    # ### end Alembic commands ###
