"""user_actions

Revision ID: c737091a66ad
Revises: c5a583453c74
Create Date: 2023-05-07 16:30:22.467716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c737091a66ad'
down_revision = 'c5a583453c74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS_ACTIONS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_unique_name', sa.String(length=30), nullable=False),
    sa.Column('action_type', sa.Enum('LESSON', 'LESSON_CANCELLATION', 'SUBSCRIPTION', name='useractiontype'), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('subs_quantity', sa.Integer(), nullable=True),
    sa.Column('subs_cancellations', sa.Integer(), nullable=True),
    sa.Column('subs_valid_from', sa.DateTime(), nullable=True),
    sa.Column('subs_valid_to', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_USERS_ACTIONS_user_id'), 'USERS_ACTIONS', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_USERS_ACTIONS_user_id'), table_name='USERS_ACTIONS')
    op.drop_table('USERS_ACTIONS')
    # ### end Alembic commands ###
